/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteRouteImport } from './routes/_chat/route'
import { Route as ChatIndexRouteImport } from './routes/_chat/index'
import { Route as SettingsUsageRouteImport } from './routes/settings/usage'
import { Route as SettingsToolsRouteImport } from './routes/settings/tools'
import { Route as SettingsProvidersRouteImport } from './routes/settings/providers'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsModelsRouteImport } from './routes/settings/models'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as ChatChatChatIdRouteImport } from './routes/_chat/chat.$chatId'

const SettingsRouteLazyRouteImport = createFileRoute('/settings')()

const SettingsRouteLazyRoute = SettingsRouteLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/settings/route.lazy').then((d) => d.Route),
)
const ChatRouteRoute = ChatRouteRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRouteRoute,
} as any)
const SettingsUsageRoute = SettingsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any)
const SettingsToolsRoute = SettingsToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any)
const SettingsModelsRoute = SettingsModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRouteLazyRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatChatIdRoute = ChatChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => ChatRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/settings': typeof SettingsRouteLazyRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/tools': typeof SettingsToolsRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/': typeof ChatIndexRoute
  '/chat/$chatId': typeof ChatChatChatIdRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRouteLazyRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/tools': typeof SettingsToolsRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/': typeof ChatIndexRoute
  '/chat/$chatId': typeof ChatChatChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteRouteWithChildren
  '/settings': typeof SettingsRouteLazyRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/models': typeof SettingsModelsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/tools': typeof SettingsToolsRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/chat/$chatId': typeof ChatChatChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/auth/sign-in'
    | '/settings/appearance'
    | '/settings/models'
    | '/settings/profile'
    | '/settings/providers'
    | '/settings/tools'
    | '/settings/usage'
    | '/'
    | '/chat/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/auth/sign-in'
    | '/settings/appearance'
    | '/settings/models'
    | '/settings/profile'
    | '/settings/providers'
    | '/settings/tools'
    | '/settings/usage'
    | '/'
    | '/chat/$chatId'
  id:
    | '__root__'
    | '/_chat'
    | '/settings'
    | '/auth/sign-in'
    | '/settings/appearance'
    | '/settings/models'
    | '/settings/profile'
    | '/settings/providers'
    | '/settings/tools'
    | '/settings/usage'
    | '/_chat/'
    | '/_chat/chat/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRouteRoute: typeof ChatRouteRouteWithChildren
  SettingsRouteLazyRoute: typeof SettingsRouteLazyRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRouteRoute
    }
    '/settings/usage': {
      id: '/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof SettingsUsageRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/tools': {
      id: '/settings/tools'
      path: '/tools'
      fullPath: '/settings/tools'
      preLoaderRoute: typeof SettingsToolsRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/models': {
      id: '/settings/models'
      path: '/models'
      fullPath: '/settings/models'
      preLoaderRoute: typeof SettingsModelsRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRouteLazyRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/chat/$chatId': {
      id: '/_chat/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatChatIdRouteImport
      parentRoute: typeof ChatRouteRoute
    }
  }
}

interface ChatRouteRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
  ChatChatChatIdRoute: typeof ChatChatChatIdRoute
}

const ChatRouteRouteChildren: ChatRouteRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
  ChatChatChatIdRoute: ChatChatChatIdRoute,
}

const ChatRouteRouteWithChildren = ChatRouteRoute._addFileChildren(
  ChatRouteRouteChildren,
)

interface SettingsRouteLazyRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsModelsRoute: typeof SettingsModelsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsToolsRoute: typeof SettingsToolsRoute
  SettingsUsageRoute: typeof SettingsUsageRoute
}

const SettingsRouteLazyRouteChildren: SettingsRouteLazyRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsModelsRoute: SettingsModelsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsToolsRoute: SettingsToolsRoute,
  SettingsUsageRoute: SettingsUsageRoute,
}

const SettingsRouteLazyRouteWithChildren =
  SettingsRouteLazyRoute._addFileChildren(SettingsRouteLazyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ChatRouteRoute: ChatRouteRouteWithChildren,
  SettingsRouteLazyRoute: SettingsRouteLazyRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
